---
- name: De-Install IIS Web servie
  hosts: windows
  gather_facts: true
  
  tasks:
  - name: stop iis service
    win_service:
      name: W3SVC
      state: stopped
        
  - name: de-install iis
    win_feature:
      name: Web-Server
      state: absent
      restart: yes
      include_sub_features: yes
      include_management_tools: yes