---
- name: Install IIS Web servie
  hosts: windows
  gather_facts: true
  
  tasks:
    - name: install iis
      win_feature:
        name: Web-Server
        state: present
        restart: yes
        include_sub_features: yes
        include_management_tools: yes
    - name: start iis service
      win_service:
        name: W3SVC
        state: started
    - name: Create website index.html
      win_copy:
        content: "<html><body><h1>Out site is alive!</h1><p><h3>{{ site_test_msg }}</h3></body></html>"
        dest: C:\Inetpub\wwwroot\index.html